### ISSUE TITLE
Unexpected input(s) 

### ISSUE THREAD

**Issue by gyeongwon1275** [CodeSoom/project-react-3-gyeongwon1275#39]
```yml
 name: Make env file
 uses: SpicyPizza/create-envfile@v1
 with: 
   envkey_BASEURL: ${{secrets.BASEURL}}
   directory: ./front
   file_name: .env.production
```
